plugins {
    id "net.fabricmc.fabric-loom"
}

base {
    archivesName = "${rootProject.mod_id}-fabric"
}

sourceSets {
    main {
        java.srcDirs += ["../common/src/main/java"]
        resources.srcDirs += ["../common/src/main/resources"]
        java.exclude(
                "pepjebs/mapatlases/client/AtlasInHandRenderer.java",
                "pepjebs/mapatlases/client/CompoundTooltip.java",
                "pepjebs/mapatlases/client/MapVertexConsumer.java",
                "pepjebs/mapatlases/client/screen/**",
                "pepjebs/mapatlases/integration/fabric/**",
                "pepjebs/mapatlases/map_collection/fabric/CCStuff.java",
                "pepjebs/mapatlases/integration/JEICompat.java",
                "pepjebs/mapatlases/integration/REICompat.java",
                "pepjebs/mapatlases/integration/SpecialRecipeDisplays.java",
                "pepjebs/mapatlases/integration/moonlight/AtlasOnlyDecorationRenderer.java",
                "pepjebs/mapatlases/integration/moonlight/CustomDecorationButton.java",
                "pepjebs/mapatlases/integration/moonlight/EntityPinDecoration.java",
                "pepjebs/mapatlases/integration/moonlight/EntityPinDecorationRenderer.java",
                "pepjebs/mapatlases/integration/moonlight/EntityPinMarker.java",
                "pepjebs/mapatlases/integration/moonlight/PinDecoration.java",
                "pepjebs/mapatlases/integration/moonlight/PinDecorationRenderer.java",
                "pepjebs/mapatlases/integration/moonlight/PinMarker.java",
                "pepjebs/mapatlases/mixin/CartographyTableScreenMixin.java",
                "pepjebs/mapatlases/mixin/ClientBoundMapPacketMixin.java",
                "pepjebs/mapatlases/mixin/CompatTFMapRendererMixin.java",
                "pepjebs/mapatlases/mixin/ItemInHandRendererMixin.java",
                "pepjebs/mapatlases/mixin/LecternRendererMixin.java",
                "pepjebs/mapatlases/mixin/MapRendererMixin.java",
                "pepjebs/mapatlases/mixin/QuickPlayLogHackMixin.java",
                "pepjebs/mapatlases/mixin/WorldSelectionListMixin.java"
        )
    }
}

loom {
    mods {
        "${rootProject.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    implementation "io.github.llamalad7:mixinextras-fabric:${mixin_extras_version}"
}

processResources {
    def replaceProperties = [
            minecraft_version    : minecraft_version,
            minecraft_min_version: minecraft_min_version,
            minecraft_max_version: minecraft_max_version,
            mod_id               : mod_id,
            mod_name             : mod_name,
            mod_version          : mod_version,
            mod_license          : mod_license,
            mod_authors          : mod_authors,
            mod_description      : mod_description,
            mod_credits          : mod_credits,
            mod_homepage         : mod_homepage,
            mod_github           : mod_github,
            cca_version          : cca_version
    ]

    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties + [project: project]
    }
}
