plugins {
    id "base"
    id "net.fabricmc.fabric-loom" version "1.15.5" apply false
}

allprojects {
    group = rootProject.mod_group_id
    version = rootProject.mod_version

    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.terraformersmc.com/releases/" }
        maven { url = "https://maven.shedaniel.me/" }
        maven { url = "https://maven.ladysnake.org/releases" }
        maven { url = "https://api.modrinth.com/maven" }
    }
}

subprojects {
    apply plugin: "java"

    base {
        archivesName = rootProject.mod_id
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(rootProject.java_version as int)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = rootProject.java_version as int
    }
}
