org.gradle.jvmargs = -Xmx5096M
org.gradle.daemon = false

# Mc stuff
minecraft_version = 26.1
minecraft_min_version = 26.1
minecraft_max_version = 26.2
java_version = 25

# Mod stuff
mod_version = 26.1-6.0.21
mod_id = map_atlases
mod_name = Map Atlases
mod_license = GPL3
mod_group_id = pebjebs.mapatlases
mod_authors = MehVahdJukaar, Pepperoni__Jabroni__
mod_credits = Pepperoni__Jabroni__, Plantkillable
mod_description= A vanilla-friendly mini-map/world-view mod using vanilla Maps, introducing the Atlas
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge
mod_github = https://github.com/MehVahdJukaar/mapatlases-neoforge/issues

project_id_fabric = 436298
modrinth_id_fabric = map-atlases

# Loaders
fabric_loader_version = 0.18.5
fabric_api_version=0.144.4+26.1

mixin_extras_version = 0.4.1
modmenu_version = 4.0.0
cloth_version = 11.0.99
emi_version = 0.7.3
trinkets_version = 3.7.0
cca_version = 8.0.0-alpha.4+26.1-rc-2
